apiVersion: v1
kind: ConfigMap
metadata:
  name: is-aruco-detector-config
  namespace: default
data:
  config: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_uri": "http://zipkin.default",
      "config": {
        "cpu_parallelism": 2,
        "dictionary": "DICT_4X4_50",
        "lengths": {
          "0": 0.17,
          "1": 0.17,
          "2": 0.17,
          "3": 0.17,
          "4": 0.17,
          "5": 0.17,
          "6": 0.17,
          "7": 0.40,
        }
      }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "is-aruco-detector"
spec:
  selector:
    matchLabels:
      app: is-aruco-detector
  replicas: 4
  template:
    metadata:
      labels:
        app: is-aruco-detector
    spec:
      containers:
      - name: service 
        image: labvisio/is-aruco-detector:0.0.5
        command: ["/service.bin"]
        args: ["/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1.0"
            memory: 256Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      volumes:
      - name: options
        configMap:
          name: is-aruco-detector-config
          items:
          - key: config
            path: options.json

---


# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: is-aruco-detector
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: extensions/v1beta1
#     kind: Deployment
#     name: is-aruco-detector
#   minReplicas: 1
#   maxReplicas: 8
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       targetAverageUtilization: 75
